export const SocketEvents = {
  // Connection / Auth
  HYDRATE_STATE: "HYDRATE_STATE",
  HEARTBEAT: "HEARTBEAT",
  
  // Participant
  PARTICIPANT_JOINED: "PARTICIPANT_JOINED",
  PARTICIPANT_LEFT: "PARTICIPANT_LEFT",
  RAISE_HAND: "RAISE_HAND",
  PARTICIPANT_HAND_RAISED: "PARTICIPANT_HAND_RAISED",
  MODERATE_USER: "MODERATE_USER",

  // Chat
  CHAT_MESSAGE: "CHAT_MESSAGE",
  CHAT_MESSAGE_RECEIVED: "CHAT_MESSAGE_RECEIVED",

  // Canvas
  DRAW: "DRAW",
  DRAW_UPDATE: "DRAW_UPDATE",
  CLEAR_CANVAS: "CLEAR_CANVAS",
  CANVAS_CLEARED: "CANVAS_CLEARED",

  // Polls
  START_POLL: "START_POLL",
  POLL_STARTED: "POLL_STARTED",
  STOP_POLL: "STOP_POLL",
  POLL_STOPPED: "POLL_STOPPED",
  SUBMIT_POLL_VOTE: "SUBMIT_POLL_VOTE",
  POLL_VOTE_RECEIVED: "POLL_VOTE_RECEIVED",

  // Screen Share / WebRTC
  REQUEST_SCREEN_SHARE: "REQUEST_SCREEN_SHARE",
  START_SCREEN_SHARE: "START_SCREEN_SHARE",
  SCREEN_SHARE_STARTED: "SCREEN_SHARE_STARTED",
  STOP_SCREEN_SHARE: "STOP_SCREEN_SHARE",
  SCREEN_SHARE_STOPPED: "SCREEN_SHARE_STOPPED",
  WEBRTC_OFFER: "WEBRTC_OFFER",
  WEBRTC_OFFER_RECEIVED: "WEBRTC_OFFER_RECEIVED",
  WEBRTC_ANSWER: "WEBRTC_ANSWER",
  WEBRTC_ANSWER_RECEIVED: "WEBRTC_ANSWER_RECEIVED",
  WEBRTC_ICE_CANDIDATE: "WEBRTC_ICE_CANDIDATE",
  WEBRTC_ICE_CANDIDATE_RECEIVED: "WEBRTC_ICE_CANDIDATE_RECEIVED",

  // Resources
  ADD_RESOURCE: "ADD_RESOURCE",
  EDIT_RESOURCE: "EDIT_RESOURCE",
  REMOVE_RESOURCE: "REMOVE_RESOURCE",
  RESOURCE_ADDED: "RESOURCE_ADDED",
  RESOURCE_UPDATED: "RESOURCE_UPDATED",
  RESOURCE_REMOVED: "RESOURCE_REMOVED",

  // Reactions
  EMOJI_REACTION: "EMOJI_REACTION",
  EMOJI_REACTION_RECEIVED: "EMOJI_REACTION_RECEIVED",
} as const;
